-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 17, 2024 at 06:09 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `artikel_wisata_cirebon`
--

-- --------------------------------------------------------

--
-- Table structure for table `wisata`
--

CREATE TABLE `wisata` (
  `id` int(11) NOT NULL,
  `nama` varchar(256) NOT NULL,
  `deskripsi` text NOT NULL,
  `lokasi` varchar(256) DEFAULT NULL,
  `kategori` varchar(256) DEFAULT NULL,
  `lon` int(11) DEFAULT NULL,
  `lat` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `wisata`
--

INSERT INTO `wisata` (`id`, `nama`, `deskripsi`, `lokasi`, `kategori`, `lon`, `lat`) VALUES
(1, 'Keraton Kasepuhan', 'Keraton Kasepuhan dahulu bernama Keraton Pakungwati, dengan Caruban Nagari sebagai kerajaannya. Sekarang Keraton Kesepuhan menjadi objek wisata unggulan Kota Cirebon, didirikan oleh Syekh Syarif Hidayatullah pada 1529 M atau 1451 tahun saka oleh Pangeran Mas Mochammad Arifin II bergelar Panembahan Pakungwati I (cicit dari Sunan Gunung Jati) yang menggantikan tahta dari Sunan Gunung Jati pada tahun 1506, beliau bersemayam di dalem Agung Pakungwati Cirebon. Sebutan Pakungwati berasal dari nama Ratu Dewi Pakungwati binti Pangeran Cakrabuana yang menikah dengan Sunan Gunung Jati. Putri itu cantik rupawan berbudi luhur dan bertubuh kokoh serta dapat mendampingi suami, baik dalam bidang Islamiyah, pembina negara maupun sebagai pengayom yang menyayangi rakyatnya. Nama Kasepuhan sendiri muncul setelah pelantikan Sultan Sepuh I yaitu PR Samsudin Martawijaya pada tahun 1679 (tercatat pada Daghregister gehouden in casteel Batavia 1624-1682 : RH Unang Sunardjo, SH).\r\n\r\nBanyak objek daya tarik wisata di Keraton Kasepuhan seperti acara Pesisir Cirebon yang di dalamnya terdapat acara kirab budaya yaitu pawai budaya yang diikuti oleh beberapa kabupaten/kota di Jawa Barat diantaranya Kabupaten Cirebon, Kabupaten Majalengka, Kabupaten Kubingan serta Kabupaten Indramayu. Dalam acara Kirab Budaya ini, masing-masing kabupaten/kota menunjukan atraksi budaya yang dimiliki oleh daerahnya. Selain itu ada festival topeng nusantara, festival keraton nusantara, grebeg syawal, dan lain-lain.\r\n\r\nFasilitas pendukung yang berada di Keraton ini adalah museum yang berisi barang peninggalan sejarah dari Kesultanan terdahulu, kantor pengelola keraton, pemadu wisata, sanggar tari, tempat pementasan, pertunjukan, telepon umum, toilet umum, serta tempat parkir kendaraan pengunjung. Keraton kasepuhan berada di wilayah kelurahan Kasepuhan, kecamatan Lemahwungkuk. Dari terminal harjamukti arahnya ke timur laut, sekitar 20 menit dengan naik becak atau 30 menit dari stasiun Kejaksaan ke arah selatan.\r\n\r\n', NULL, NULL, NULL, NULL),
(2, 'Keraton Kanoman', 'Keraton Kanoman didirikan oleh Sultan Kanoman I (Sultan Badridin) turunan ke VII dari Sunan Gunung Jati (Syarief Hidayatullah) pada tahun 510 tahun Saka atau tahun 1588 Masehi, Adapun prasasti tahun berdirinya Keraton Kanoman terdapat pada pintu Pandopa Jinem yang menuju ke ruangan Perbayaksa, di pintu tersebut terpahat gambar angka Surya Sangkala & Chandra Sangkala dengan pengertian sebagai berikut :\r\n\r\nMatahari artinya angka 1 (satu)\r\nWayang Darma Kusumah artinya angka 5 (lima)\r\nBumi artinya angka 1 (satu)\r\nBintang Kemangmang artinya angka 0 (nol)\r\nJadi terbaca tahun 1510 Saka atau tahun 1588 Masehi. Lambang angka tahun terdiri dari 2 macam yaitu Surya Sangkala dengan gambar matahari dan Chandra Sangkala dengan gambar Bulan.\r\nDari sisi silsilah para sultan, keraton kanoman mengalami silsilah yang cukup pajang. Berikut ini merupakan silsilah para sultan Keraton Kanoman:\r\n\r\nSunan Gunung Jati Syech Hidayahtullah\r\nPanembahan Pasarean Muhammad Tajul Arifin\r\nPanembahan Sedang Kemuning\r\nPanembahan Ratu Cirebon\r\nPanembahan Mande Gayem\r\nPanembahan Girilaya\r\nPara Sultan :\r\nSultan Kanoman I (Sultan Badridin)\r\nSultan Kanoman II ( Sultan Muhamamad Chadirudin)\r\nSultan Kanoman III (Sultan Muhamamad Alimudin)\r\nSultan Kanoman IV (Sultan Muhamamad Chadirudin)\r\nSultan Kanoman V (Sultan Muhamamad Imammudin)\r\nSultan Kanoman VI (Sultan Muhamamad Kamaroedin I)\r\nSultan Kanoman VII (Sultan Muhamamad Kamaroedin )\r\nSultan Kanoman VIII (Sultan Muhamamad Dulkarnaen)\r\nSultan Kanoman IX (Sultan Muhamamad Nurbuat)\r\nSultan Kanoman X (Sultan Muhamamad Nurus)\r\nSultan Kanoman XI (Sultan Muhamamad Jalalludin)\r\nSultan Kanoman XII ( Sultan Muhammad Emirrudin) sultan sekarang yang syah.\r\nJalan masuk ke Keraton Kanoman berada ada disalah satu lubang tembok tinggi berbentuk lengkung, melewati pasar, sebuah area hijau luas dengan tembok tinggi di sebelah kiri, melewati gerbang dengan ukiran yang indah.', NULL, NULL, NULL, NULL),
(3, 'Keraton Kacirebonan', 'Keraton Kecirebonan dibangun pada tahun 1800 dengan menggunakan uang pensiunan oleh Ratu Raja Resminingpuri. Pembangunan dimulai dengan bangunan induk, paseban dan tajug. Seperti bangunan keraton pada masa itu, bangunan induk merupakan tempat tinggal sehari-hari sultan beserta keluarganya. Bangunan ini terdiri dari ruang tidur, ruang kerja sultan, pecira (ruang menyimpan benda kuno istana), kamar jimat, prabayasa (ruang besar di sayap bangunan), dapur dan teras (berfungsi sebagai ruang tunggu bila prajurit rendahan ingin menghadap Sultan).\r\n\r\nBangunan ke dua bernama Paseban yang berada di sebelah kiri dan kanan kraton atau dikenal dengan nama Paseban Kulon dan Paseban Wetan. Paseban berbentuk persegi Panjang, ditompang oleh 8 buah tiang dan 4 saka guru (tiang utama) dan merupakan bangunan semi terbuka, dengan dinding sisi barat dan timur dipagari dengan tembok rendah, atapnya berbentuk joglo dengan penutup genteng. Paseban berfungsi sebagai tempat penerima tamu dan latihan tari, yakni tari topeng khas Cirebon. Sementara Tajug merupakan bangunan Musholla.  Keraton ini banyak menyimpan benda-benda peninggalan sejarah seperti Keris Wayang, Terdapat banyak peninggalan yang dapat dilihat, seperti perabotan meja dan kursi terbuat dari kayu yang hingga kini masih asli. Di dindingnya terpajang foto-foto dari kesultanan Cirebon dari dulu hingga sekarang. Di dalam pendopo terdapat berbagai macam peninggalan yang tersimpan rapi dalam etalase, diantaranya ada keris, pedang, buku, beberapa guci pemberian negara tetangga, uang kuno / uang bolong, perlengkapan perang, gamelan, hingga koleksi baju pengantin.\r\n\r\nKeraton Kacirebonan adalah pecahan dari Keraton Kanoman yang luasnya sekitar 2,5 hektar. Hal ini berawal pada saat Keraton Kanoman dipimpin oleh Sultan Kanoman ke IV yang bernama Pangeran Haerudhin pada tahun 1670-an. Pengaruh Kolonial Belanda telah masuk ke dalam Kedaulatan Kesultanan Kanoman, dan hal ini di tentang keras oleh Putra Mahkota Sultan Kanoman ke IV yang bernama Pangeran Muhamad Haerudhin. Pangeran Muhamad Haerudhin melakukan perlawanan terbuka dengan Pemerintah Kolonial Belanda. Perlawanan ini mendapat reaksi yang positif dari masyarakat cirebon, sehingga perlawanan ini berlangsung sekurangnya 5 tahun. Pada tahun 1696 Pangeran Muhamad Haerudhin berhasil dilumpuhkan dan diasingkan ke Ambon, Maluku. Melihat keadaan Pangeran Haerudhin yang telah lanjut usia, maka pemerintah Kolonial Belanda secara sepihak (unilateral) mengangkat Pangeran Imammudin sebagai Sultan Kanoman ke V.', NULL, NULL, NULL, NULL),
(4, 'Keraton Kaprabon', 'Bangunan yang didirikan pada tahun 1703 M oleh Adipati Peguron ini merupakan tempat tinggal beliau yang memutuskan untuk meninggalkan dunia keraton dan memilih mendalami ilmu agama dan tarekat. Nuansa religius akan langsung terasa saat memasuki kompleks Peguron Keprabon yang berkarakter, sederhana dan nyaman yang terdiri dari beberapa bangunan yang tersekat oleh tembok; di dalamnya terdapat pula sebuah pesantren yang menjadi tempat menimba dan mengajarkan ilmu agama.', NULL, NULL, NULL, NULL),
(5, 'Masjid Agung Cipta Rasa', 'Pembangunan Masjid Agung Sang Cipta Rasa diprakarsai oleh Sunan Gunung Jati dan melibatkan para sunan lainnya pada tahun 1498 M. Masjid ini merupakan pengewanjatahan dari rasa dan kepercayaan. Menurut cerita rakyat yang berkembang dimasyarakat Cirebon, masjid ini dibangun hanya dalam tempo satu malam; pada dini hari berikutnya telah dipergunakan untuk shalat subuh. Masjid ini memiliki bentuk arsitektur yang unik dan indah serta sarat akan makna-makna religious yang dikandungnya. \r\nDi beranda samping kanan (utara) masjid, terdapat sumur zamzam atau Banyu Cis Sang Cipta Rasa yang ramai dikunjungi orang, terutama pada bulan Ramadhan. Selain diyakini berkhasiat untuk mengobati berbagai penyakit, sumur yang terdiri dari dua kolam ini juga dapat digunakan untuk menguji kejujuran seseorang.', NULL, NULL, NULL, NULL),
(6, 'Situs Kalijaga', 'Daya tarik wisata Situs Kalijaga merupakan tempat petilasan Sunan KaliJaga pada saat menyiarkan agama islam di Cirebon. Pada zaman dahulu kala tempat ini merupakan sebuah hutan yang lebat. Atas prakarsa Sunan Kalijaga, kemudian dibangunlah sebuah taman yang indah dan asri sebagai tempat beliau mengajarkan ilmu agama kepada masyarakat Cirebon. Keunikan dari situs ini adalah selain suasananya yang teduh dan menyegarkan, tempat ini juga merupakan habitat asli sekumpulan kera yang jinak dan kerap turun menghampiri pengunjung.', NULL, NULL, NULL, NULL),
(7, 'Gua Sunyaragi', 'Tamansari Gua Sunyaragi atau dikenal dengan sebutan Gua Sunyaragi, adalah sebuah bekas taman sari pesanggrahan dari Keraton Kasepuhan yang fungsi utamanya untuk menyepi atau berkhawalat, sesuai dengan namanya. Sunyaragi yang berarti tempat untuk menyepi atau mengasingkan raga (sunya berarti sepi dan ragi berarti raga). Sebutan gua yang dimaksud dalam hal ini bukanlah gua alam, melainkan gua artificial. Dengan kata lain gaya arsitektur tamansari ini banyak menyerupai gua yang berhiaskan air dan itulah yang menjadi daya tarik utama dari taman sari dari taman Gua Sunyaragi. Tradisi mengatakan, bahwa Tamansari Gua Sunyaragi didirikan sejak 1488 Saka (gajah derum tirta linuwih; gajah = , derum = 4, tirta = 4, linuwih = 1) atau tahun 1526 M oleh Panembahan Gusti Ratu Pakungwati I atau PM Muhammda Arifin II. Dari Keraton Kasepuhan ke Gua Sunyaragi mengarah ke barat daya, hanya berjarak ± 3,5 km.\r\nPetilasan dengan arsitektur estetik bernilai historis, serta mengungkap nilai-nilai spritual yang merupakan salah satu warisan budaya masa lalu yang terdapat di wilayah Cirebon, Pembangunannya dilakukan pada tahun 1703, sedangkan gagasannya berasal dari benak Sang Patih Keraton Kasepuhan yang bernama Pangeran Arya Cirebon. Tokoh ini dikenal sebagai peminta sejarah dan kebudayaan. Karya legendaris lainnya yaitu kitab sejarah “Purwaka Caruban” yang berhasil disusunnya pada tahun 1720. Sunya berarti sepi, dan Raga atau Ragi berarti jasmani.', NULL, NULL, NULL, NULL),
(8, 'Pedati Gede', 'Pedati Gede Pekalangan merupakan salah satu benda bersejarah yang memiliki 3 pasang roda belakang berdiameter 2,5 m dan sepasang roda berukuran kecil pada bagian kursinya. Panjang kerbau penariknya adalah ± 15 m. Pedati ini berfungsi sebagai alat angkut kayu untuk pembangunan Masjid Agung Sang Cipta Rasa pada abad ke-15. Pada jaman Panembahan Giri Laya kereta ini berfungsi sebagai kendaraan untuk melawat ke daerah-daerah.', NULL, NULL, NULL, NULL),
(9, 'Taman Ade Irma Suryani', 'Ade Irma Waterpark diresmikan pada 1 Juli 2015 oleh Walikota Cirebon Nasrudin Aziz. Cirebon Waterland berdiri di atas lahan seluas 3 Ha dengan penambahan dari Taman Ade Irma Suryani yang merupkan aset milik Pemkot Kota Cirebon. WaterLand Ade Irma Cirebon ini terletak di Jalan Dipenogoro Kota Cirebon, lokasinya berdekatan dengan Kantor Bank Indonesia cabang Cirebon. Dikabarkan tempat ini akan di adakan Grand Opening yang akan dilaksanakan pada awal Desember 2015. Untuk harga tiket masuk dikenakan biaya sekitar Rp 50.000 per orangnya. kehadiran tempat ini diharapkan juga dapat menarik wisatawan dari luar daerah Cirebon dan tidak menutup kemungkinan untuk wisatawan mancanegara singgah di tempat ini.\r\nAde Irma Suryani Waterpark ini memiliki tiga macam kolam air yang tak jauh dari pintu masuk waterpark. yaitu waterboom khusus untuk anak-anak, kolam ber-arus untuk anak maupun dewasa dan kolam renang olimpic berkedalaman 1,5 meter bagi dewasa. tak hanya kolamnya saja, Wahana taman bermain darat juga tak kalah ramainya. Taman ini dilengkapi dengan pasir putih layaknya di pantai, ada ayunan serta miniatur kapal yang terbuat dari kayu. Melalui tangga dan jembatan rintangan, pengunjung juga bisa naik kapal. Saat ini, manajemen Waterpark juga tengah menyiapkan wahana lain, yaitu speedboot, Waterboom untuk dewasa dan wahana ombak air, pengelola saat ini juga berencana melengkapi tempat ini dengan restoran jepang. Di tempat ini juga menyediakan cottege yang saat ini tersedia 18 unit yang siap digunakan untuk tempat istirahat. Bangunan cottage disini mengambil desain arsitektur rumah adat Minang yang beratapkan bentuk limas dan berdiri di atas pantai. Bangunan cottege disini juga berkonsep seperti yang ada di Pulau Seribu atau yang ada di Bali.\r\nUntuk harga sewa permalam di cottege ini bervariasi, tergantung dari pemandangan dan luasnya. Untuk cottage pool view dikenakan harga Rp 1,5 juta per malam, sementara cottage sea view dikenakan harga Rp 1,7 juta per malam dan Untuk cottege yang dapat menampung banyak anggota dikenakan harga Rp 2,5 juta per malamnya. Harga tersebut sudah termasuk paket breakfast dan wahana di Waterland. Untuk para pengunjung yang ingin menuju ke obyek wisata Ade Irma Suryani Waterpark, dapat di akses melalui pintu gerbang Tol Palimanan Cirebon, dari arah Jakarta bisa mengambil rute Jalan Panglima Sudirman atau Jalan Raya Aryawinangun-Palimanan, sampai lokasi sekitar 35 menit. Jika melalui arah Jawa Tengah dapat mengambil rute Jalan Pantura, Jarak tempuh lokasi Waterland dari perbatasan Jawa Tengah-Jawa Barat, Losari, sekitar 32 km atau sekitar 40 menit menggunakan kendaraan pribadi.', NULL, NULL, NULL, NULL),
(10, 'Pantai Kejawanan', 'Pantai Kejawanan merupakan salah satu daya tarik wisata bahari di Kota Cirebon. Hamparan laut yang tenang, semilir angin yang lembut adalah beberapa dari sekian banyak keunikan yang dapat dinikmati dipantai ini. Menikmati sunset atau sunrise dari Pantai Kejawanan, menjadikan para pengunjung sulit untuk melupakan suasana wisata bahari di Kota Cirebon yang sulit dilupakan. Pantai ini juga memiliki nilai tambah lain, yaitu terdapat pemandian alami yang berkhasiat untuk mengobati berbagai penyakit luar maupun dalam yang masih dipercaya oleh masyarakat lokal pada umumnya.\r\n\r\nWisatawan dapat berkeliling pantai dengan perahu nelayan dengan tarif Rp.5000,- per orang yang tentunya cukup terjangkau, itupun dapat dapat ditawar hingga Rp.3000,- per orang. Selain itu, disana tersedia sewa perahu karet dengan tarif Rp.5000,- sampai dengan Rp.10.000,- per satu jamnya, wisatawan dapat menikmati indanya sunset dengan tempat terbaik di pantai Kejawanan dengan harga yang tentunya tidak merogoh kocek yang terlalu dalam alias murah.', NULL, NULL, NULL, NULL),
(11, 'Kawasan Pecinan Kuno', 'Kawasan Pecinan Kuno di Kota Cirebon merupakan living monument yang sudah ada sebelum kedatangan Kolonial Belanda. Nuansa dan suasana Cina di kawasan ini begitu terasa ditandai oleh bentuk pemukiman dan aktivitas yang terdapat di kawasan ini. Bentuk pemukiman yang menandai kawasan sebagai Pecinan terlihat dari bangunan-bangunan yang menghadap jalan besar begitu sempit namun panjang ke belakang. Selain itu bangunan yang merupakan tanda dari bangunan Cina adalah bangunan di sini berderet rapih terutama pada bagian depannya dan deretan ada di antara jalan besar atau sebaliknya gang-gang sempit. Biasanya muka bangunan yang sempit itu dipergunakan sebagai toko atau tempat bisnis lain.\r\n\r\nKawasan ini merupakan Chinatown di kota Cirebon juga dipertegas dengan banyaknya bangunan-bangunan tempat ibadah yang identik dengan etnis Tionghoa di kawasan ini. Bangunan-bangunan tempat ibadah tersebut terutama adalah Vihara Dewi Welas Asih, Klenteng Winaon (Klenteng Pemancar Keselamatan), dan Klenteng Talang. Bangunan-bangunan tersebut menambah nuansa dan suasana Cina, di antaranya dominasi warna merah dengan sekali-kali warna kuning keemasan mewarnai bangunan-bangunan ini.\r\n\r\nSementara itu di Jalan Lemahwungkuk terdapat toko atau kios yang menjual obat-obatan / jamu tradisional Cina. Toko atau kios ini menjual obat-obatan / jamu tradisional Cina untuk semua jenis penyakit, seperti wasir. Jalan ini dikenal juga dengan pusat penjualan burung atau yang termasuk keluarga burung, walaupun demikian di sinipun dijual hewan-hewan lainnya seperti kucing, kelinci, marmut, hamster, penyu, ikan, dan bahkan binatang melata, seperti ular dan iguana.\r\n\r\nSelain itu Jalan Lemahwungkuk dikenal dengan pusat jajanan malam harinya. Jajanan yang dijual bukan hanya makanan khas Cirebon, seperti sate kalong, tetapi juga jajanan-jajanan lainnya, mulai dari jajanan pasar (orang kabupaten menyebutnya dado pasar). Sementara minuman yang tersedia di sini meliputi skoteng, bajigur, es kelapa, es juice, dan lain-lainnya. Deretan penjual makanan di jalan ini dikenal dengan Pujamari, yakni singkatan dari Pusat Jajan Malam Hari. Sedangkan Jalan Pecinan yang menghubungkan Jalan Lemahwungkuk dengan Jalan Talang dan Jalan Merdeka dikenal dengan pusat penjualan barang-barang bekas. ', NULL, NULL, NULL, NULL),
(12, 'Kampung Benda', 'Kesenian dan Kebudayaan Kampung Benda sangat dikenal dengan keagamaannya dan religinya, karena banyak sekali pondok-pondok pesantren disini. Pakaian yang harus dikenakan juga harus sesuai dengan aturan yaitu dengan memakai pakaian islami. Pakaian untuk pria itu seperti kopeah dan sarung sedangkan pakaian untuk perempuan disini adalah wajib memakai rok baju panjang dan wajib memakai kerudung. Di Kampung Benda ini tidak diperbolehkan memakai celana panjang karena dikatakan sebagai para penjajah Belanda.\r\n\r\nKesenian di kampung benda ini diataranya; 1). alat musiknya seperti rebana dan gembyung, dan 2). seni beladirinya adalah silat/ beladiri Arab yang diberi nama Detik. Alat Musik Rebana dan gembyung ini dimainkan saat ada acara hari raya Idul Adha (raya agung), acara muludan dan acara nikahan ataupun khitanan isinya berupa shalawat.', NULL, NULL, NULL, NULL),
(13, 'Watu Celek', 'Situs Batu Lingga atau Watu Celek berada di dalam bangunan persegi yang ukurannya sekitar 2×2 meter persegi. Bangunannya berwarna orange. Selain Batu Celek, dalam bangunan itu terdapat Makam Ki Datuk Pardun, yang konon merupakan murid Syekh Siti Jenar. Tinggi batu tersebut sekitar 50 sentimeter. Lokasinya berada di tempat kuliner pedagang kaki lima (PKL) di depan Pasar Kramat, samping Gedung Bank BJB Kota Cirebon. Kabarnya, manajemen bank tersebut menghormati benda itu sebagai tinggalan masa silam. Mirip kemaluan, dan inilah yang disebut-sebut unik itu. Ternyata bentuk batu ini mirip kemaluan pria. Konon, karena bentuknya yang unik itulah maka orang-orang banyak menziarahi batu dan makam ini. Mereka datang dari berbagai tempat, baik dari Cirebon sendiri, Majalengka, Kuningan, bahkan dari Bandung.\r\n\r\nFilolog Cirebon Raden Opan Raffan Hasyim menyebutkan sejarah tentang Situs Watu Celek dan Makam Kit Datuk Pardun memiliki keterikatan. Namun, sejarah tentang keduanya hanya ada dalam satu manuskrip yakni tentang sejarah akhir Cirebon. Menurut Opan Situs Watu Celek merupakan sindiran terhadap Ki Datuk Pardun.', NULL, NULL, NULL, NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `wisata`
--
ALTER TABLE `wisata`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `wisata`
--
ALTER TABLE `wisata`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
